[tasks.hello]
script = [
'''
#!/usr/bin/env bash
echo Hello, World!
'''
]

# kinesis
[tasks.kinesis-get-shard-iterator]
script = [
'''
#!/usr/bin/env bash
aws kinesis get-shard-iterator --stream-name $1 --shard-id shardId-000000000000 --shard-iterator-type AT_SEQUENCE_NUMBER --starting-sequence-number $2 --profile $3
'''
]

[tasks.kinesis-get-records]
script = [
'''
#!/usr/bin/env bash
aws kinesis get-records --shard-iterator $1 --profile $2 | jq .Records[0].Data | base64 --decode
'''
]